//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIPA.Data.AccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppData
    {
        public string BusinessName { get; set; }
        public string Supervisor { get; set; }
        public bool Enabled { get; set; }
        public System.Guid Instance { get; set; }
    }
}
