//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIPA.Data.AccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Communicator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Communicator()
        {
            this.Devices = new HashSet<Device>();
        }
    
        public int Id { get; set; }
        public int StartChar { get; set; }
        public int EndChar { get; set; }
        public System.DateTime LastReadTime { get; set; }
        public CommunicatorType Type { get; set; }
        public ValueType ValueType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual IEnumerable<Device> Devices { get; set; }
    }
}
