//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIPA.Data.AccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCIPAEntities : DbContext
    {
        public SCIPAEntities()
            : base("name=SCIPAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Communicator> Communicators { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<Rule> Rules { get; set; }
        public virtual DbSet<Value> Values { get; set; }
        public virtual DbSet<AppData> AppData { get; set; }
    }
}
