//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIPA.Data.AccessLayer
{
    using System;
    
    public enum RuleType : short
    {
        LessThan = 0,
        LessThanEqualTo = 1,
        EqualTo = 2,
        MoreThanEqualTo = 3,
        MoreThan = 4,
        Not = 5,
        Between = 6
    }
}
