//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIPA.Data.AccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerialCommunicator : Communicator
    {
        public string ComPort { get; set; }
        public int BaudRate { get; set; }
        public byte DataBits { get; set; }
        public bool IsRTS { get; set; }
        public bool IsDTR { get; set; }
    }
}
