//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIPA.Data.AccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Value
    {
        public int Id { get; set; }
        public string EventTime { get; set; }
        public string StringValue { get; set; }
        public string Inbound { get; set; }
        public int DeviceId { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
